### ISSUE TITLE
Allow jump directions

### ISSUE THREAD

**Issue by jdloft** [thestandardtoaster/html5-physics#3]
When in normal gravity the active object jumps (or performs a dynamic acceleration change) in the up direction. When the gravity is inverted the object only floats in the direction that it should go. A configuration option should be created that allows these different jump directions so that the object could actually jump down.

**Comment by thestandardtoaster** [comment]
I will get right on that

**Comment by thestandardtoaster** [comment]
Fixed, jumping is now opposite gravity à la commit ae4e6

**Comment by jdloft** [comment]
Very nice. Fetching...

**Comment by jdloft** [comment]
Works well. Although I noticed that you removed the double jump limit. I can jump forever!
